### ISSUE TITLE
[Issue] read_channel_status Method Returns Empty, Zero, or Default Values in Demo Script

### ISSUE THREAD

**Issue by devanshiAppperfect** [BattGenie/pycti#13]
**Description -**
When running the demo script, I've noticed that the `read_channel_status` method is returning empty, zero, or default values. I would like to understand why this is happening and if there are any known reasons for this behaviour.

**Steps to Reproduce -**
1. Execute the demo script.
2. Specifically, observe the output of the `read_channel_status` method for cell 3

**Screenshot -**
![Screenshot 2023-12-21 at 3 18 44 PM](https://github.com/BattGenie/pycti/assets/111724834/c5a0e9cd-8427-4a47-9528-4337ad113a5b)

**Question:**
Additionally, I am interested in connecting the library to an external stimulator to obtain actual data. Is there any guidance or documentation available on how to achieve this integration?

Any assistance or insights into these matters would be greatly appreciated.

Thank you!!

**Comment by SyXuan** [comment]
Hello, in the `demo_notebook.ipynb` example, `ArbinSpoofer` is used to simulate an Arbin Cycler. You can refer to `arbin_spoofer.py` for more details. In the init method, all fields will have default values. Therefore, if you want `ArbinSpoofer` to return different values, you can refer to the following code to modify the voltage field:

```python
arbin_spoofer.update_channel_status(0, {'voltage_v': 1.234})
```

**Comment by devanshiAppperfect** [comment]
@SyXuan, while the update_channel_status method allows us to update values, I'm actually looking to retrieve raw data from PyCTI. How can I achieve that?
I was previously using read_channel_status method but it seems like that the values provided by that method are null or empty. Why so ?
My primary objective is to obtain real data from PyCTI using spoofers. Could you provide guidance on that ?

**Comment by SyXuan** [comment]
Please follow the `demo_notebook.ipynb` with your cycler credentials to fetch the raw data

**Comment by devanshiAppperfect** [comment]
I am not using any cycler. I want to connect using spoofers. Is there any schedular file for that ?

**Comment by chintanp** [comment]
@devanshiAppperfect generating data is not in the scope of `pycti` or `pymacnet`. We did write small implementation of cycler spoofer, but the intent was only to support development, testing, and debugging since hardware access cannot be guaranteed in remote work environments. 

If you want mock data, then you can try a package like Faker (https://faker.readthedocs.io/en/master/index.html) to generate mock data. What the data format for different fields should be can be determined from the cycler output or CTI/MacNet docs. 

To have the data look exactly like a real li-ion cell, you need a battery model. The better and more accurate the model, the closer the mocked or modeled data will be to a real cell.

**Comment by chintanp** [comment]
@devanshiAppperfect this folder has a sample schedule and resulting data file. Let me know if you have further questions.

**Comment by devanshiAppperfect** [comment]
@chintanp  Could you please specify which folder you are referring to?
